import { YoutubeTranscript } from 'youtube-transcript';
import { Transcript, TranscriptSegment } from '@/types';

export interface TranscriptOptions {
  lang?: string;
  country?: string;
}

export interface AvailableCaption {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

/**
 * Service for extracting transcripts from YouTube videos
 */
export class TranscriptService {
  /**
   * Extract transcript from a YouTube video
   */
  static async extractTranscript(
    videoId: string, 
    options: TranscriptOptions = {}
  ): Promise<Transcript> {
    try {
      const transcriptData = await YoutubeTranscript.fetchTranscript(videoId, {
        lang: options.lang || 'en'
      });

      // Convert youtube-transcript format to our Transcript interface
      const segments: TranscriptSegment[] = transcriptData.map((item) => ({
        text: item.text,
        startTime: item.offset / 1000, // Convert milliseconds to seconds
        endTime: (item.offset + item.duration) / 1000,
        confidence: 1.0 // youtube-transcript doesn't provide confidence scores
      }));

      const totalDuration = segments.length > 0 
        ? segments[segments.length - 1].endTime 
        : 0;

      return {
        segments,
        language: options.lang || 'en',
        confidence: 1.0, // Default confidence for available transcripts
        duration: totalDuration
      };
    } catch (error) {
      throw new Error(`Failed to extract transcript: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Get available captions/subtitles for a video
   * Note: youtube-transcript doesn't provide a direct way to list available captions
   * This is a simplified implementation that attempts common languages
   */
  static async getAvailableCaptions(videoId: string): Promise<AvailableCaption[]> {
    const commonLanguages = [
      { code: 'en', name: 'English' },
      { code: 'es', name: 'Spanish' },
      { code: 'fr', name: 'French' },
      { code: 'de', name: 'German' },
      { code: 'it', name: 'Italian' },
      { code: 'pt', name: 'Portuguese' },
      { code: 'ru', name: 'Russian' },
      { code: 'ja', name: 'Japanese' },
      { code: 'ko', name: 'Korean' },
      { code: 'zh', name: 'Chinese' }
    ];

    const availableCaptions: AvailableCaption[] = [];

    for (const lang of commonLanguages) {
      try {
        await YoutubeTranscript.fetchTranscript(videoId, { lang: lang.code });
        availableCaptions.push({
          languageCode: lang.code,
          languageName: lang.name,
          isAutoGenerated: true // We can't determine this with youtube-transcript
        });
      } catch {
        // Language not available, continue to next
        continue;
      }
    }

    return availableCaptions;
  }

  /**
   * Check if transcript is available for a video
   */
  static async isTranscriptAvailable(videoId: string, lang = 'en'): Promise<boolean> {
    try {
      await YoutubeTranscript.fetchTranscript(videoId, { lang });
      return true;
    } catch {
      return false;
    }
  }
}