import { GET } from '../route';
import { TranscriptService } from '@/lib/transcript-service';
import { extractVideoId } from '@/lib/youtube-utils';
import { NextRequest } from 'next/server';

// Mock dependencies
jest.mock('@/lib/transcript-service');
jest.mock('@/lib/youtube-utils');

const mockTranscriptService = TranscriptService as jest.Mocked<typeof TranscriptService>;
const mockExtractVideoId = extractVideoId as jest.MockedFunction<typeof extractVideoId>;

describe('/api/youtube/captions', () => {
  const originalConsoleError = console.error;
  
  beforeAll(() => {
    console.error = jest.fn();
  });

  afterAll(() => {
    console.error = originalConsoleError;
  });

  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('GET', () => {
    it('should get available captions using URL parameter', async () => {
      const mockCaptions = [
        {
          languageCode: 'en',
          languageName: 'English',
          isAutoGenerated: true
        },
        {
          languageCode: 'es',
          languageName: 'Spanish',
          isAutoGenerated: true
        }
      ];

      mockExtractVideoId.mockReturnValue('test-video-id');
      mockTranscriptService.getAvailableCaptions.mockResolvedValue(mockCaptions);

      const request = new NextRequest('http://localhost:3000/api/youtube/captions?url=https://www.youtube.com/watch?v=test-video-id');
      const response = await GET(request);
      const data = await response.json();

      expect(response.status).toBe(200);
      expect(data).toEqual({
        success: true,
        data: {
          videoId: 'test-video-id',
          availableCaptions: mockCaptions
        }
      });
      expect(mockExtractVideoId).toHaveBeenCalledWith('https://www.youtube.com/watch?v=test-video-id');
      expect(mockTranscriptService.getAvailableCaptions).toHaveBeenCalledWith('test-video-id');
    });

    it('should get available captions using videoId parameter', async () => {
      const mockCaptions = [
        {
          languageCode: 'en',
          languageName: 'English',
          isAutoGenerated: true
        }
      ];

      mockTranscriptService.getAvailableCaptions.mockResolvedValue(mockCaptions);

      const request = new NextRequest('http://localhost:3000/api/youtube/captions?videoId=direct-video-id');
      const response = await GET(request);
      const data = await response.json();

      expect(response.status).toBe(200);
      expect(data).toEqual({
        success: true,
        data: {
          videoId: 'direct-video-id',
          availableCaptions: mockCaptions
        }
      });
      expect(mockTranscriptService.getAvailableCaptions).toHaveBeenCalledWith('direct-video-id');
    });

    it('should return empty captions array when none available', async () => {
      mockExtractVideoId.mockReturnValue('test-video-id');
      mockTranscriptService.getAvailableCaptions.mockResolvedValue([]);

      const request = new NextRequest('http://localhost:3000/api/youtube/captions?url=https://www.youtube.com/watch?v=test-video-id');
      const response = await GET(request);
      const data = await response.json();

      expect(response.status).toBe(200);
      expect(data).toEqual({
        success: true,
        data: {
          videoId: 'test-video-id',
          availableCaptions: []
        }
      });
    });

    it('should return 400 when no URL or videoId provided', async () => {
      const request = new NextRequest('http://localhost:3000/api/youtube/captions');
      const response = await GET(request);
      const data = await response.json();

      expect(response.status).toBe(400);
      expect(data).toEqual({
        error: 'Either url or videoId parameter is required'
      });
    });

    it('should return 400 when URL is invalid', async () => {
      mockExtractVideoId.mockReturnValue(null);

      const request = new NextRequest('http://localhost:3000/api/youtube/captions?url=invalid-url');
      const response = await GET(request);
      const data = await response.json();

      expect(response.status).toBe(400);
      expect(data).toEqual({
        error: 'Invalid YouTube URL format'
      });
    });

    it('should return 500 when service fails', async () => {
      mockExtractVideoId.mockReturnValue('test-video-id');
      mockTranscriptService.getAvailableCaptions.mockRejectedValue(
        new Error('Service unavailable')
      );

      const request = new NextRequest('http://localhost:3000/api/youtube/captions?url=https://www.youtube.com/watch?v=test-video-id');
      const response = await GET(request);
      const data = await response.json();

      expect(response.status).toBe(500);
      expect(data).toEqual({
        error: 'Failed to check available captions',
        details: 'Service unavailable'
      });
    });

    it('should handle unknown error types', async () => {
      mockExtractVideoId.mockReturnValue('test-video-id');
      mockTranscriptService.getAvailableCaptions.mockRejectedValue('Unknown error');

      const request = new NextRequest('http://localhost:3000/api/youtube/captions?url=https://www.youtube.com/watch?v=test-video-id');
      const response = await GET(request);
      const data = await response.json();

      expect(response.status).toBe(500);
      expect(data).toEqual({
        error: 'Failed to check available captions',
        details: 'Unknown error occurred'
      });
    });
  });
});